version: '3'

services:
  postgresql:
    image: bitnami/postgresql:14.17.0
    container_name: postgresql
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata: